### ISSUE TITLE
Allotment - Typedefinition not found

### ISSUE THREAD

**Issue by argawow** [johnwalley/allotment#717] opened 2023-11-04 08:51 UTC
I have changed my React-Project to Vite and now I have problems to import allotment. It works like expected, but when it comes to the production build i get this error

` Could not find a declaration file for module 'allotment'. 'C:/.....s/visualstudio/projekte/....C/client-app/node_modules/allotment/dist/modern.mjs' implicitly has an 'any' type.
  There are types at 'C:....../client-app/node_modules/allotment/dist/types/src/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'allotment' library may need to update its package.json or typings.

8 import  { Allotment, AllotmentHandle } from "allotment";`

Can some help me out here?

**Comment by vojtatom** [comment] 2023-11-07 11:55
Same issue here with npm 10.1.0 when using this package in Next.js project.

**Comment by vojtatom** [comment] 2023-11-07 11:55
seems like a duplicate of https://github.com/johnwalley/allotment/issues/669

**Comment by johnwalley** [comment] 2023-12-28 01:20
Looking into this. I've got a variety of Vite and NextJS projects to, hopefully, reproduce this against.

**Comment by johnwalley** [comment] 2023-12-28 01:51
I'd appreciate it if you could see if `v1.19.4` helps?

**Comment by InsidersByte** [comment] 2024-01-03 14:57
@johnwalley it's fixed for me (using Next.js v14.0.3)

**Closed** 2024-04-10 22:00 UTC
